### ISSUE TITLE
[FEATURE REQUEST] SpotifyControls - Toggle to swap the player location from bottom to top

### ISSUE THREAD

**Issue by FL4MIN** [Vendicated/Vencord#2112]
### Content

Dear devs,
Could be possible to kindly consider adding a toggle to swap the player location from bottom to top in SpotifyControls plugin?

- Example:
![image](https://github.com/Vendicated/Vencord/assets/32968126/59a6749f-889c-486e-8f09-9d61893fca4e)

_If the request really goes against the rules please delete it or redirect me to the right place.
I couldn't find any other place where to make a feature request (checked on Discord already)._

### Request Agreement

- [x] I have read the requirements for opening an issue above

**Comment by cheesesamwich** [comment]
me when css

**Comment by Vendicated** [comment]
I wrote this snippet a year ago idk if it still works. use the support channel next time
```css
[class|=panels] {
    display: flex;
    flex-direction: column;
}

#vc-spotify-player {
    order: -1;
}
```
