### ISSUE TITLE
[QoL] Proposed UI fix for betterFolders sidebar

### ISSUE THREAD

**Issue by sander1946** [Vendicated/Vencord#3348]
### Content

Hello, 
I use Better Folders on Vesktop, however the sidebar has been moved to the left side since the new discord UI update. I however do not like how it looks. The way it's now the folder expands way above the top of the original guild bar. 
I did some digging into the CSS of discord and Vesktop and have added these CSS snippets to my QuickCSS. I would like it to be added to the source code. I looked into adding it myself and creating a pull request, but I could not figure that out. So I would like to leave it here for you guys to add if you guys want to.
I was not able to prevent the sidebar from scrolling past the top bar, this is because the sidebar is not a part of the base unlike the original, I also can't extend the bottom of the sidebar to go past the user information bar, this is because changing the size of the sidebar also changes the size of the original resulting in guilds not being assessable

If there are any questions, or improvements. Feel free to ask about it!

<details>
  <summary>CSS</summary>
```CSS
/* Move folder icons on the left side down to match the second row */
div[class*='isExpanded']:has(ul[role~="group"]) {
    margin-top: var(--custom-app-top-bar-height);
}

/* Prefent the icon in the original guildbar from also getting the margin */
div[class^='base'] div[class*='isExpanded']:has(ul[role~="group"]) {
    margin-top: auto;
}
```
</details>

<details>
  <summary>Original look:</summary>

![Image](https://github.com/user-attachments/assets/c9622cbc-a14d-46e9-9329-aa471442d8ad)

![Image](https://github.com/user-attachments/assets/cca4d1ce-8070-40c8-997f-a998941e00d1)

![Image](https://github.com/user-attachments/assets/9f501111-12f8-4bc5-a147-9049d04835bc)

</details>

<details>
  <summary>My proposal:</summary>

![Image](https://github.com/user-attachments/assets/b3a9a58f-2195-450e-bcd4-6f83d3b738ce)

![Image](https://github.com/user-attachments/assets/052ba676-ae66-408c-b10d-1415e625738d)

![Image](https://github.com/user-attachments/assets/56a960cb-893c-44a4-81cb-4f76c64db444)

![Image](https://github.com/user-attachments/assets/d19cacbb-de28-4af9-98db-360dcdc98a58)`

![Image](https://github.com/user-attachments/assets/042235bc-9c25-4de3-812b-ae14e45e9d64)
</details>

### Request Agreement

- [x] I have read the requirements for opening an issue above
